package simulator.core;

import simulator.config.SimulationConfig;
import simulator.model.*;
import simulator.model.Process;
import simulator.io.SimulationEventListener;

/**
 * The main engine of the simulation (The Clock).
 * Controls the passage of time (ticks) and orchestrates interactions
 * between the scheduler, virtual memory, processors, and the system process.
 * Implements an Observer pattern (via SimulationEventListener) to
 * decouple internal logic from display systems (text file, graphical interface).
 */
public class SimulationEngine {

    /** Global configuration read from the input file. */
    private final SimulationConfig config;

    /** Array simulating physical processing units (CPU). */
    private final Processor[] processors;

    /** Complete list of user processes to be simulated. */
    private final UserProcess[] allUserProcesses;

    /** High-priority process responsible for system calls (I/O). */
    private final SystemProcess systemProcess;

    /** The scheduling strategy used (in this case, Round-Robin with affinity). */
    private final SchedulingStrategy scheduler;

    /** Component responsible for RAM management and LRU policy. */
    private final MemoryManager memoryManager;

    // --- Observer Pattern ---
    /** Internal array of listeners for engine events. */
    private final SimulationEventListener[] listeners = new SimulationEventListener[10];

    /** Current number of registered listeners. */
    private int listenerCount = 0;

    /** Global simulation time, measured in abstract units (ticks). */
    private int globalTime = 0;

    /** Number of user processes that have completely finished execution. */
    private int completedProcesses = 0;

    /**
     * Constructs and initializes the simulation engine.
     *
     * @param config    System parameter configuration.
     * @param processes Array of processes read and ready for launch.
     */
    public SimulationEngine(SimulationConfig config, UserProcess[] processes) {
        this.config = config;
        this.allUserProcesses = processes;

        // Initialize processors
        this.processors = new Processor[config.getNumProcessors()];
        for (int i = 0; i < config.getNumProcessors(); i++) {
            this.processors[i] = new Processor(i);
        }

        // Initialize key components
        this.systemProcess = new SystemProcess(0, config.getSystemProcessPeriod());
        this.scheduler = new Scheduler();
        this.memoryManager = new MemoryManager(config.getTotalRAM(), config.getDiskTransferRate());
    }

    /**
     * Registers a new listener for events generated by the simulator.
     *
     * @param listener Object implementing the SimulationEventListener interface.
     */
    public void addEventListener(SimulationEventListener listener) {
        if (listenerCount < listeners.length) {
            listeners[listenerCount++] = listener;
        }
    }

    /**
     * Sends a text message to all registered listeners.
     *
     * @param message The event text.
     */
    private void log(String message) {
        for (int i = 0; i < listenerCount; i++) {
            listeners[i].onLogMessage(message);
        }
    }

    /**
     * Notifies graphical listeners about processor activity at the current tick.
     *
     * @param cpuId     ID of the active processor.
     * @param processId ID of the executed process (0 for system).
     * @param tick      Current time.
     */
    private void notifyCpuUsage(int cpuId, int processId, int tick) {
        for (int i = 0; i < listenerCount; i++) {
            listeners[i].onCpuExecution(cpuId, processId, tick);
        }
    }

    /**
     * Notifies graphical listeners about hard disk activity
     * (virtual memory transfer) at the current tick.
     *
     * @param processId ID of the process transferred from disk.
     * @param tick      Current time.
     */
    private void notifyDiskUsage(int processId, int tick) {
        for (int i = 0; i < listenerCount; i++) {
            listeners[i].onDiskExecution(processId, tick);
        }
    }

    /**
     * Starting point of the simulation. Runs a continuous time loop
     * until all user processes reach the TERMINATED state.
     * Includes a safety timeout at T=20000 to prevent infinite loops.
     */
    public void run() {
        log("=== Start Simulation ===");

        while (completedProcesses < allUserProcesses.length) {
            executeTick();
            globalTime++;

            // Infinite loop safety
            if (globalTime > 20000) {
                log("Simulation was forcibly stopped (Timeout) at T=20000.");
                break;
            }
        }

        log("=== Simulation Finished at T=" + globalTime + " ===");
    }

    /**
     * Central method called at each time unit.
     * Checks for new launches, memory transfers, executes one step
     * for processes on processors, checks preemption conditions,
     * and calls the scheduler.
     */
    private void executeTick() {
        // 1. Check for new launches
        for (int i = 0; i < allUserProcesses.length; i++) {
            if (allUserProcesses[i].getReleaseTime() == globalTime && allUserProcesses[i].getCurrentState() == ProcessState.NEW) {
                logEvent(globalTime, "ENGINE", "Process " + allUserProcesses[i].getId() + " has been launched into the system.");
                ((Scheduler)scheduler).addProcess(allUserProcesses[i]);
            }
        }

        // 2. Manage Virtual Memory (Disk -> RAM Transfer)
        if (memoryManager.isSwapping()) {
            notifyDiskUsage(memoryManager.getSwappingProcess().getId(), globalTime - 1);
        }

        Process swappedInProcess = memoryManager.executeSwapTick();
        if (swappedInProcess != null) {
            logEvent(globalTime, "MEMORY", "Process " + swappedInProcess.getId() + " has fully entered RAM.");
            // ANTI-THRASHING FIX: Enters directly at the front of the queue!
            //((Scheduler)scheduler).addProcessToFront(swappedInProcess);
            ((Scheduler)scheduler).addProcess(swappedInProcess);
        }

        // 3. Check if the System Process (VIP) wakes up
        if (systemProcess.checkReleaseTime()) {
            if (systemProcess.getCurrentState() != ProcessState.RUNNING) {
                logEvent(globalTime, "VIP", "System Process (0) woke up. Moving to READY state.");
                systemProcess.setState(ProcessState.READY);
            }
        }

        // 4. Advance time on processors
        for (int i = 0; i < processors.length; i++) {
            Processor cpu = processors[i];

            if (!cpu.isIdle()) {
                notifyCpuUsage(cpu.getId(), cpu.getCurrentProcess().getId(), globalTime - 1);
                cpu.executeTick(globalTime);
                Process p = cpu.getCurrentProcess();

                // 4.A. VIP Logic
                if (p instanceof SystemProcess) {
                    UserProcess finishedUserP = ((SystemProcess) p).getFinishedIoProcess();
                    if (finishedUserP != null) {
                        if (finishedUserP.getCurrentState() == ProcessState.TERMINATED) {
                            completedProcesses++;
                            logEvent(globalTime, "VIP", "Finished I/O task. Process " + finishedUserP.getId() + " has been permanently TERMINATED.");
                        } else {
                            ((Scheduler)scheduler).addProcess(finishedUserP);
                            logEvent(globalTime, "VIP", "Finished I/O for Process " + finishedUserP.getId() + ". Sending it back to Scheduler (READY).");
                        }
                    }
                    if (p.getCurrentState() == ProcessState.WAITING_IO) {
                        logEvent(globalTime, "VIP", "Finished all I/O requests. Going to sleep and releasing CPU " + cpu.getId() + ".");
                        cpu.evictProcess();
                    }
                }
                // 4.B. Normal process termination
                else if (p.getCurrentState() == ProcessState.TERMINATED) {
                    cpu.evictProcess();
                    completedProcesses++;
                    logEvent(globalTime, "CPU", "Process " + p.getId() + " has completed its execution. Releasing CPU " + cpu.getId() + ".");
                }
                // 4.C. I/O Blocking
                else if (p instanceof UserProcess && ((UserProcess) p).isCurrentlyDoingIo()) {
                    logEvent(globalTime, "CPU", "Process " + p.getId() + " is blocking for System Call (I/O). Releasing CPU " + cpu.getId() + ".");
                    p.setState(ProcessState.WAITING_IO);
                    systemProcess.requestSystemCall((UserProcess) cpu.evictProcess());
                }
                // 4.D. Preemption (Time Slice Expired)
                else if (cpu.isTimeSliceExpired()) {
                    Process evicted = cpu.evictProcess();
                    if (evicted instanceof UserProcess) {
                        logEvent(globalTime, "CPU", "Process " + evicted.getId() + " ran out of Time Slice. Moving to READY.");
                        ((Scheduler)scheduler).addProcess(evicted);
                    } else if (evicted instanceof SystemProcess) {
                        evicted.setState(ProcessState.READY);
                        logEvent(globalTime, "VIP", "System Process ran out of Time Slice. Moving to READY.");
                    }
                }
            }
        }

        // 5. Call the Scheduler
        scheduler.schedule(processors, systemProcess, memoryManager, config.getTimeSlice(), globalTime, this);
    }

    /**
     * Centralized method for logging.
     */
    public void logEvent(int time, String category, String message) {
        String logStr = "[T=" + time + "] [" + category + "] " + message;
        for (int i = 0; i < listenerCount; i++) {
            listeners[i].onLogMessage(logStr);
        }
    }
}